export enum PageTypeEnum{
    Home = 1,
    Security = 100,
    User = 101,
    Role = 102,
    UserRole = 103,
    Page = 104,
    Permission = 105,
    PagePermission = 106,
    RolePagePermission = 107,
    UserProfile = 108,
    ContentManagement = 200,
    PostCategory = 201,
    Post = 202,
    Link = 203,
    Slider = 204,
    Menue = 205,
    GalleyCategory = 206,
    Gallery = 207,
    Brand = 208,
    Event = 209,
    EventRegister = 210
}

export const PageTypeEnumLabelMapping:Record<PageTypeEnum, string> = {
    [PageTypeEnum.Home]: 'home',    
    [PageTypeEnum.Security]: 'security',
    [PageTypeEnum.User]: 'user',
    [PageTypeEnum.Role]: 'role',
    [PageTypeEnum.UserRole]: 'userRole',
    [PageTypeEnum.Page]: 'page',
    [PageTypeEnum.Permission]: 'permission',
    [PageTypeEnum.PagePermission]: 'pagePermission',
    [PageTypeEnum.RolePagePermission]: 'rolePagePermission',
    [PageTypeEnum.UserProfile]: 'userProfile',
    [PageTypeEnum.ContentManagement]: 'contentManagement',
    [PageTypeEnum.PostCategory]: 'postCategory',
    [PageTypeEnum.Post]: 'post',
    [PageTypeEnum.Link]: 'link',
    [PageTypeEnum.Slider]: 'slider',
    [PageTypeEnum.Menue]: 'menu',
    [PageTypeEnum.GalleyCategory]: 'galleryCategory',
    [PageTypeEnum.Gallery]: 'gallery',
    [PageTypeEnum.Brand]: 'brand',
    [PageTypeEnum.Event]: 'event',
    [PageTypeEnum.EventRegister]: 'eventRegister'
}